# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      dev-deps: { dependency-type: development }

  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      gh-actions: { patterns: ["*"] }
