#!/usr/bin/env bash
# Summary: Show the current Node version and its origin
#
# Shows the currently selected Node version and how it was
# selected. To obtain only the version string, use `nodenv
# version-name'.

set -e
[ -n "$NODENV_DEBUG" ] && set -x

VERSION_NAME="$(nodenv-version-name)"

# TODO figure out why travis requires this
if [ "$VERSION_NAME" != system ]; then
  VERSION_PATH="$(nodenv-prefix "$VERSION_NAME")"

  while [ -L "$VERSION_PATH" ]; do
    READLINK=$(type -p greadlink readlink | head -1)

    if [ -n "$READLINK" ]; then
      VERSION_PATH=$($READLINK "$VERSION_PATH")
      ALIAS=$(basename "$VERSION_PATH")
    fi
  done
fi

echo "$VERSION_NAME ${ALIAS+=> $ALIAS }(set by $(nodenv-version-origin))"
