#!/usr/bin/env bash
# Summary: List hook scripts for a given nodenv command
# Usage: nodenv hooks <command>

set -e
[ -n "$NODENV_DEBUG" ] && set -x

# Provide nodenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

NODENV_COMMAND="$1"
if [ -z "$NODENV_COMMAND" ]; then
  nodenv-help --usage hooks >&2
  exit 1
fi

IFS=: read -r -a hook_paths <<<"$NODENV_HOOK_PATH"

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$NODENV_COMMAND"/*.bash; do
    echo "$script"
  done
done
shopt -u nullglob
