#!/usr/bin/env bash
set -e
[ -n "$NODENV_DEBUG" ] && set -x

# Provide nodenv completions
if [ "$1" = "--complete" ]; then
  exec nodenv-rehash --complete
fi

# When nodenv shell integration is enabled, delegate to nodenv-rehash,
# then tell the shell to empty its command lookup cache.
nodenv-rehash
echo "hash -r 2>/dev/null || true"
