#!/usr/bin/env bash
# Usage: nodenv completions <command> [arg1 arg2...]

set -e
[ -n "$NODENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  nodenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "nodenv-$COMMAND" || command -v "nodenv-sh-$COMMAND")"
if grep -iE "^([#%]|--|//) provide nodenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
