#!/usr/bin/env bash
# Summary: Detect the file that sets the current nodenv version
set -e
[ -n "$NODENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.node-version" ]; then
      echo "${root}/.node-version"
      exit
    elif [ -e "${root}/.nodenv-version" ]; then
      echo "${root}/.nodenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$NODENV_DIR"
[ "$NODENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${NODENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${NODENV_ROOT}/global" ]; then
  echo "${NODENV_ROOT}/global"
elif [ -e "${NODENV_ROOT}/default" ]; then
  echo "${NODENV_ROOT}/default"
else
  echo "$global_version_file"
fi
