name: Test
on:
  push:
  pull_request:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:

permissions: {}
jobs:
  build:
    permissions: { contents: read }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - run: npm ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm run prepare && git diff --exit-code

  test:
    uses: nodenv/.github/.github/workflows/test.yml@bd27009d5f178c0a88d42f7b07e6a3c7623ed768 # v7.0.8
    with: { superlinter: false } # TODO re-enable superlinter
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  super-lint:
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with: { egress-policy: audit }
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { fetch-depth: 0, persist-credentials: false }
      - uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env: # FIXME resolve failures for linters below and re-enable
          GITHUB_TOKEN: ${{ github.token }}
          BASH_EXEC_IGNORE_LIBRARIES: true # superlinter bug
          FILTER_REGEX_EXCLUDE: node_modules
          VALIDATE_BIOME_FORMAT: false # conflicts with prettier
          VALIDATE_BIOME_LINT: false # conflicts with prettier
          VALIDATE_GIT_COMMITLINT: false # commitlint is bad
          VALIDATE_JSCPD: false # jscpd is false-positive prone and generally not useful
          VALIDATE_SPELL_CODESPELL: false # codespell is buggy
          # TODO remove deviations from reusable superlinter config
          VALIDATE_BASH: false
          VALIDATE_SHELL_SHFMT: false
